name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkey -v -keystore release.keystore -alias android -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Test, OU=Android, O=Test, L=City, ST=State, C=RU"
          echo "✅ Keystore generated!"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: release-keystore
          path: release.keystore
